version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: srepulse

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .

    image: sre-pulse:latest
    container_name: sre-pulse

    depends_on:
      - postgres

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/srepulse
      DEBUG: "true"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus

    depends_on:
      - fastapi

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana

    depends_on:
      - prometheus

    ports:
      - "3000:3000"

    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data: